// GENERATED by brand/build.ts. Do not edit; rerun `bun run brand/build.ts`.
//
// A lowercase `d` whose square bowl doubles as a box. The letter is currentColor so it
// follows the text; the extrusion is the only coloured part, in two values because this
// page switches themes.
import { cn } from "@/lib/utils"

const D =
  "M41,6 H52 V58 H24 A12,12 0 0 1 12,46 V33 A12,12 0 0 1 24,21 H41 Z M28,32 H36 A5,5 0 0 1 41,37 V42 A5,5 0 0 1 36,47 H28 A5,5 0 0 1 23,42 V37 A5,5 0 0 1 28,32 Z"

export function Mark({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 64 64"
      className={cn("size-8 shrink-0", className)}
      role="img"
      aria-label="devbox"
    >
      <g transform="translate(-2 -2)">
        <g transform="translate(4 4)">
          <path
            d={D}
            fillRule="evenodd"
            className="fill-[#1F8B38] dark:fill-[#3FB950]"
          />
        </g>
        <path d={D} fillRule="evenodd" fill="currentColor" />
      </g>
    </svg>
  )
}

/** The word, drawn from a 5x7 grid: no font to ship, and no fallback to go wrong. */
export function Wordmark({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 280 56"
      className={cn("h-4 w-auto shrink-0", className)}
      fill="currentColor"
      aria-hidden
    >
      <rect x="32" y="0" width="8" height="8" />
      <rect x="144" y="0" width="8" height="8" />
      <rect x="32" y="8" width="8" height="8" />
      <rect x="144" y="8" width="8" height="8" />
      <rect x="8" y="16" width="32" height="8" />
      <rect x="56" y="16" width="24" height="8" />
      <rect x="96" y="16" width="8" height="8" />
      <rect x="128" y="16" width="8" height="8" />
      <rect x="144" y="16" width="32" height="8" />
      <rect x="200" y="16" width="24" height="8" />
      <rect x="240" y="16" width="8" height="8" />
      <rect x="272" y="16" width="8" height="8" />
      <rect x="0" y="24" width="8" height="8" />
      <rect x="32" y="24" width="8" height="8" />
      <rect x="48" y="24" width="8" height="8" />
      <rect x="80" y="24" width="8" height="8" />
      <rect x="96" y="24" width="8" height="8" />
      <rect x="128" y="24" width="8" height="8" />
      <rect x="144" y="24" width="8" height="8" />
      <rect x="176" y="24" width="8" height="8" />
      <rect x="192" y="24" width="8" height="8" />
      <rect x="224" y="24" width="8" height="8" />
      <rect x="248" y="24" width="8" height="8" />
      <rect x="264" y="24" width="8" height="8" />
      <rect x="0" y="32" width="8" height="8" />
      <rect x="32" y="32" width="8" height="8" />
      <rect x="48" y="32" width="40" height="8" />
      <rect x="96" y="32" width="8" height="8" />
      <rect x="128" y="32" width="8" height="8" />
      <rect x="144" y="32" width="8" height="8" />
      <rect x="176" y="32" width="8" height="8" />
      <rect x="192" y="32" width="8" height="8" />
      <rect x="224" y="32" width="8" height="8" />
      <rect x="256" y="32" width="8" height="8" />
      <rect x="0" y="40" width="8" height="8" />
      <rect x="32" y="40" width="8" height="8" />
      <rect x="48" y="40" width="8" height="8" />
      <rect x="104" y="40" width="8" height="8" />
      <rect x="120" y="40" width="8" height="8" />
      <rect x="144" y="40" width="8" height="8" />
      <rect x="176" y="40" width="8" height="8" />
      <rect x="192" y="40" width="8" height="8" />
      <rect x="224" y="40" width="8" height="8" />
      <rect x="248" y="40" width="8" height="8" />
      <rect x="264" y="40" width="8" height="8" />
      <rect x="8" y="48" width="32" height="8" />
      <rect x="56" y="48" width="24" height="8" />
      <rect x="112" y="48" width="8" height="8" />
      <rect x="144" y="48" width="32" height="8" />
      <rect x="200" y="48" width="24" height="8" />
      <rect x="240" y="48" width="8" height="8" />
      <rect x="272" y="48" width="8" height="8" />
    </svg>
  )
}

/** Mark and word on one line, for the sign-in screen. */
export function Logo({ className }: { className?: string }) {
  return (
    <span className={cn("inline-flex items-center gap-3", className)}>
      <Mark className="size-10" />
      <Wordmark className="h-5" />
    </span>
  )
}
